In [2]:
import numpy as np

In [6]:
marks=np.random.randint(0,99,(50))
print("student marks",marks)
total=marks.sum()
average_marks=total/50

print("\nTotal of the student marks:",total)
print("\nAverage of the student marks:",average_marks)
print("\nThe highest marks:",np.max(marks))
print("\nThe lowes marks:",np.min(marks))

above_75 = np.sum(marks > 75)
below_35 = np.sum(marks < 35)
between_35_75 = np.sum((marks >= 35) & (marks <= 75))

print("\n70 above student makrs total =",above_75)
print("\n30 below student makrs total =",below_35)
print("\nbetween the 35-75 total =",between_35_75)

#5 Top and 5 Bottom student marks
top=np.sort(marks)[-5:]
bottom=np.sort(marks)[0:6]
print("\nTop 5 student mark:",top)
print("\nBottom 5 student mark:",bottom)

#median and standard deviation
print("\nMedian of the marks:",np.median(marks))
print("\nStandard Deviation of the marks",np.std(marks))

####################################
# 5 subject marks
sub_marks=np.random.randint(35,101,size=(50,5))
print("\nEach Student 5 Subject Marks:\n",sub_marks)
                    
Total=np.sum(sub_marks,axis=1)
Average=np.mean(sub_marks, axis=1)
Percentage= (Total / 500) * 100

print("5 Subject Total Of Each Student:")
for i in range(50):
    print(f"{i+1} = \t{Total[i]}")
    

topper=np.argmax(sub_marks,0)
subjects=["Marathi","HIndhi","English","Maths","Social Science"]
for i in range(5):
    print(f"{subjects[i]} : Student {topper[i]+1} Scored {sub_marks[topper[i],i]} marks")
print("=====================REPORT CARD==========================")
print("Student\tTotal\tAverage\t\tPercentage\tGrade")

grade = []

for i in range(50):

    if Percentage[i] >= 90:
        grade.append("A+")
    elif Percentage[i] >= 80:
        grade.append("A")
    elif Percentage[i] >= 70:
        grade.append("B")
    elif Percentage[i] >= 60:
        grade.append("C")
    elif Percentage[i] >= 40:
        grade.append("D")
    else:
        grade.append("F")

    print(f"{i+1}\t{Total[i]}\t{Average[i]:2f}\t{Percentage[i]:.2f}%\t\t{grade[i]}")

student marks [98 17 33 72 44 79 82 42 95 65  9 49  6 23 54 49 97  7 16 89 88 75 56 62
 78  8 48 58 17 38 75 67  3 36 90 73 27 83 74 69 38 78 13 75 57  6 41 42
 43 34]

Total of the student marks: 2578

Average of the student marks: 51.56

The highest marks: 98

The lowes marks: 3

70 above student makrs total = 11

30 below student makrs total = 14

between the 35-75 total = 25

Top 5 student mark: [89 90 95 97 98]

Bottom 5 student mark: [3 6 6 7 8 9]

Median of the marks: 51.5

Standard Deviation of the marks 27.86263447701958

Each Student 5 Subject Marks:
 [[ 49  90  82  64  83]
 [ 39  36  81  54  89]
 [ 84  84  50  56  43]
 [ 77  72  83  62  94]
 [ 92  45  35 100  60]
 [ 90  87  45  91  92]
 [ 84  93  59  38  72]
 [ 52  74  57  70  62]
 [ 58  39  73  78 100]
 [ 58  38  75  90  38]
 [ 76  90  65  62  59]
 [ 90  61  46  64  41]
 [ 55  53  53  76  68]
 [ 42  35  60  90  67]
 [ 81  66  79  68  60]
 [ 51  51  42  83  54]
 [ 79  81  47  93  50]
 [ 76  61  80  72  36]
 [ 54  76  60  63 